/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.code.gson:gson:2.8.9")
}

application {
    // Define the main class for the application.
    mainClass.set("com.github.mizzoucapstonefrontrow.managementserver.server.Server")
    val runDir = rootProject.projectDir.resolve("run")
    runDir.mkdirs()
    tasks.run.get().workingDir = runDir
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

tasks {
    withType<Jar> {
        // Make Executable
        manifest {
            attributes["Main-Class"] = application.mainClass
        }
        // Fat Jar (Include Dependencies in Build)
        from(configurations.runtimeClasspath.get().map {
            if (it.isDirectory) it
            else zipTree(it)
        })
    }
}
